### ISSUE TITLE
FastDDS Python on ARM not working

### ISSUE THREAD

**Issue by andreclerigo** [eProsima/Fast-DDS-python#106]
Hello there, since the FastDDS Suite Image is not compatible with ARM, I've tried to build my own, but I am getting some problems.

This is my Dockerfile
```Dockerfile
FROM arm64v8/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    cmake \
    libssl-dev \
    libasio-dev \
    libtinyxml2-dev \
    openjdk-11-jre-headless \
    python3 \
    vim \
    wget \
    make \
    iproute2 \
    net-tools \
    libpython3-dev \
    python3-pip \
    swig \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install colcon-common-extensions
RUN pip3 install vcstool

# Copy your /fastdds directory into the Docker image
# The fastdds directory contains the unzipped contents referenced in https://fast-dds.docs.eprosima.com/en/latest/installation/binaries/binaries_linux.html#linux-installation-from-binaries
COPY fastdds /fastdds

RUN chmod +x /fastdds/install.sh

WORKDIR /fastdds

RUN ./install.sh

RUN echo 'export LD_LIBRARY_PATH=/usr/local/lib/' >> ~/.bashrc
RUN export LD_LIBRARY_PATH=/usr/local/lib/

RUN mkdir -p /Fast-DDS-python && cd /Fast-DDS-python \
    && wget https://raw.githubusercontent.com/eProsima/Fast-DDS-python/main/fastdds_python.repos \
    && mkdir src && vcs import src < fastdds_python.repos \
    && colcon build

ENV LD_LIBRARY_PATH=/usr/local/lib/

WORKDIR /root
```

Then I proceed with the following commands
```bash
docker build -t fastdds-image .
docker run -d --ipc shareable --name ipc_share_container alpine sleep infinity
cd <directory_with_code>
docker run -itd --network host --ipc container:ipc_share_container --name message_processor -v $(pwd)/src:/root/app fastdds-image
docker exec -it message_processor su
source /Fast-DDS-python/install/setup.bash
cd app
fastddsgen -cdr v1 -python MQTTMessage.idl SimpleObjectInfo.idl
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_SHARED_LIBS=ON .
cmake --build .
cd ..
```

Then I run my Python application and get the following error:
```stderr
Traceback (most recent call last):
  File "/root/app/app.py", line 16, in <module>
    import protocols.dds as dds
  File "/root/app/protocols/dds.py", line 4, in <module>
    import build.SimpleObjectInfo as SimpleObjectInfo
  File "/root/app/build/SimpleObjectInfo.py", line 13, in <module>
    from . import _SimpleObjectInfoWrapper
ImportError: /root/app/build/libSimpleObjectInfo.so: undefined symbol: _ZN8eprosima7fastcdr11deserializeI16SimpleObjectInfoEEvRNS0_3CdrERT_
```

When using FastDDS Suite Docker Image on a amd64 architecture I follow similar steps
```
docker run -d --ipc shareable --name ipc_share_container alpine sleep infinity
cd <directory_with_code>
docker run -itd --network host --ipc container:ipc_share_container --name message_processor -v $(pwd)/src:/root/app fastdds-image
docker exec -it message_processor su
cd app
fastddsgen -cdr v1 -python MQTTMessage.idl SimpleObjectInfo.idl
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/ -DBUILD_SHARED_LIBS=ON .
cmake --build .
cd ..
# then run the application without any errors
```

I am guessing that, since I am using an image that compiles the source code of fastdds I am missing a flag or env variable somewhere.

**Comment by andreclerigo** [comment]
Got it working, seems that the problem was the --cdr v1 flag on the fastddsgen command.
